import Head from 'next/head'
import Image from 'next/image'
import axios from "axios"
import styles from '../styles/Home.module.css'
import PostLists from '../Components/PostLists';
import Sidebar from '../Components/Sidebar';
import Header from '../Components/Header';
import {NEXT_URL} from "../url"


export default function Home({product}) {
  console.log(product);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
{/* <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossOrigin="anonymous"/> */}

      </Head>
      <Header />
      <div className={styles.postpage}>
      <PostLists product={product} />
      <Sidebar />
      </div>

     
    </div>
  )
}
export async function  getServerSideProps () {
  const res = await axios.get(NEXT_URL + "/api/post")
  console.log(res.data);
  return {
    props: {
      product:res.data
    },
  }
}
